export const ActionTypes = {
  FETCH_COINS: "FETCH_COINS",
  FETCH_COINS_CHART: "FETCH_COINS_CHART",
  // FETCH_COINS_ASYNC: "FETCH_COINS_ASYNC",
  // FETCH_COINS_CHART_ASYNC: "FETCH_COINS_CHART_ASYNC",
};
